// Code generated by protoc-gen-go. DO NOT EDIT.
// source: forecaster.proto

package forecaster

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Weather struct {
	Unit                 string   `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Temperature          int32    `protobuf:"varint,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Weather) Reset()         { *m = Weather{} }
func (m *Weather) String() string { return proto.CompactTextString(m) }
func (*Weather) ProtoMessage()    {}
func (*Weather) Descriptor() ([]byte, []int) {
	return fileDescriptor_888c7c50cfd3b4ea, []int{0}
}

func (m *Weather) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Weather.Unmarshal(m, b)
}
func (m *Weather) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Weather.Marshal(b, m, deterministic)
}
func (m *Weather) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Weather.Merge(m, src)
}
func (m *Weather) XXX_Size() int {
	return xxx_messageInfo_Weather.Size(m)
}
func (m *Weather) XXX_DiscardUnknown() {
	xxx_messageInfo_Weather.DiscardUnknown(m)
}

var xxx_messageInfo_Weather proto.InternalMessageInfo

func (m *Weather) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Weather) GetTemperature() int32 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func (m *Weather) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Forecast struct {
	Weathers             []*Weather `protobuf:"bytes,1,rep,name=weathers,proto3" json:"weathers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Forecast) Reset()         { *m = Forecast{} }
func (m *Forecast) String() string { return proto.CompactTextString(m) }
func (*Forecast) ProtoMessage()    {}
func (*Forecast) Descriptor() ([]byte, []int) {
	return fileDescriptor_888c7c50cfd3b4ea, []int{1}
}

func (m *Forecast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Forecast.Unmarshal(m, b)
}
func (m *Forecast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Forecast.Marshal(b, m, deterministic)
}
func (m *Forecast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Forecast.Merge(m, src)
}
func (m *Forecast) XXX_Size() int {
	return xxx_messageInfo_Forecast.Size(m)
}
func (m *Forecast) XXX_DiscardUnknown() {
	xxx_messageInfo_Forecast.DiscardUnknown(m)
}

var xxx_messageInfo_Forecast proto.InternalMessageInfo

func (m *Forecast) GetWeathers() []*Weather {
	if m != nil {
		return m.Weathers
	}
	return nil
}

func init() {
	proto.RegisterType((*Weather)(nil), "forecaster.Weather")
	proto.RegisterType((*Forecast)(nil), "forecaster.Forecast")
}

func init() { proto.RegisterFile("forecaster.proto", fileDescriptor_888c7c50cfd3b4ea) }

var fileDescriptor_888c7c50cfd3b4ea = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xcb, 0x2f, 0x4a,
	0x4d, 0x4e, 0x2c, 0x2e, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0xc5, 0x72, 0xb1, 0x87, 0xa7, 0x26, 0x96, 0x64, 0xa4, 0x16, 0x09, 0x09, 0x71, 0xb1, 0x94,
	0xe6, 0x65, 0x96, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x0a, 0x5c, 0xdc,
	0x25, 0xa9, 0xb9, 0x05, 0xa9, 0x45, 0x89, 0x25, 0xa5, 0x45, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a,
	0xac, 0x41, 0xc8, 0x42, 0x42, 0x32, 0x5c, 0x9c, 0x25, 0x99, 0xb9, 0xa9, 0xc5, 0x25, 0x89, 0xb9,
	0x05, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x08, 0x01, 0x25, 0x6b, 0x2e, 0x0e, 0x37, 0xa8,
	0x65, 0x42, 0xfa, 0x5c, 0x1c, 0xe5, 0x10, 0xab, 0x8a, 0x25, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d,
	0x84, 0xf5, 0x90, 0xdc, 0x06, 0x75, 0x46, 0x10, 0x5c, 0x51, 0x12, 0x1b, 0xd8, 0xb9, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x0e, 0x52, 0xf7, 0xc2, 0x00, 0x00, 0x00,
}
