version: '2.1'

services:
  forecaster:
    image: kramerdust/forecaster
    container_name: forecaster-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      GOPATH: '/go'
    env_file:
      - '.env'