// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package app

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonDadbda93DecodeGithubComKramerdustWeatherReporterInternalApp(in *jlexer.Lexer, out *WeatherAPIModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "city":
			out.City = string(in.String())
		case "unit":
			out.Unit = string(in.String())
		case "temperature":
			out.Temperature = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDadbda93EncodeGithubComKramerdustWeatherReporterInternalApp(out *jwriter.Writer, in WeatherAPIModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix[1:])
		out.String(string(in.City))
	}
	{
		const prefix string = ",\"unit\":"
		out.RawString(prefix)
		out.String(string(in.Unit))
	}
	{
		const prefix string = ",\"temperature\":"
		out.RawString(prefix)
		out.Int(int(in.Temperature))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WeatherAPIModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDadbda93EncodeGithubComKramerdustWeatherReporterInternalApp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WeatherAPIModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDadbda93EncodeGithubComKramerdustWeatherReporterInternalApp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WeatherAPIModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDadbda93DecodeGithubComKramerdustWeatherReporterInternalApp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WeatherAPIModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDadbda93DecodeGithubComKramerdustWeatherReporterInternalApp(l, v)
}
